### ISSUE TITLE
docker running export metrics for sidecar mode.

### ISSUE THREAD

**Issue by kyos0109** [jonnenauha/prometheus_varnish_exporter#39]
* **Varnish** `6.0.1`
* **prometheus_varnish_exporter** `1.4.1`

------------------
Hi.
Thank you for making such a great software.

Now, I'm run this software in my docker-compose and kubernetes.
I using sidecar mode running varnish container with varnish exporter container.
As I see it, maybe this solution is user friendly.

docker-compose example:
```
version: '2.4'
services:
  varnish:
    image: kyos0109/varnish60-distroless
    container_name: varnish
    hostname: varnish-server
    volumes:
      - ./conf/default-test.val:/default.vcl
      - varnish-data:/var/lib/varnish
    command: ["-f", "/default.vcl"]
    ports:
      - 8080:80
    networks:
      happy:
  varnish-exporter:
    image: kyos0109/prometheus-varnish-exporter
    pid: "service:varnish"
    network_mode: "service:varnish"
    ipc: "container:varnish"
    volumes:
      - varnish-data:/var/lib/varnish
    depends_on:
      - varnish
  web:
    image: nginx:alpine
    pid: "service:haproxy"
    ipc: "container:haproxy"
    network_mode: "service:haproxy"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - haproxy
volumes:
  varnish-data:
    driver: local
networks:
  happy:
    driver: bridge
```
But...
I met a problem.
docker container console show message:
> Could not get hold of varnishd, is it running?
 
I assume that, maybe varnish-export container exec varnishstats too early,
int 1 varnish container not ready running varnishd.
So, I modify some content, add flag --startup-delay in main() .
> kyos0109/prometheus_varnish_exporter@25d53337da671ac7c2f26239deaa1d4d84c542b4

Let you refer.
Thinks.
