### ISSUE TITLE
Varnish 4 backend UUID causing metric churn

### ISSUE THREAD

**Issue by filippog** [jonnenauha/prometheus_varnish_exporter#8]
Hi,
at Wikimedia Foundation we are trying varnish_exporter and came across some metric churn with Varnish 4, particularly on backend identity changing when reloading VCL.
The way we've worked around it is via Prometheus metric relabeling in the form of dropping the UUID altogether:

```
    metric_relabel_configs: 
      - regex: "varnish_backend_.+;root:[-a-f0-9]+\x5c.(.*)"
        source_labels: 
          - "__name__"
          - id
        target_label: id
```

This isn't really an issue per-se in varnish_exporter, though it might be useful to point out to others if they come across the same. There's also more context here: https://phabricator.wikimedia.org/T150479

Thanks!
